name: Version Bump

on:
  pull_request:
    types: [opened, labeled]

permissions:
  contents: write
  pull-requests: read

jobs:
  enforce-label-version-release:
    name: 'Enforce Labels: release: patch, release: minor, release: major'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Enforce version release labels
        uses: yogevbd/enforce-label-action@2.1.0
        with:
          REQUIRED_LABELS_ANY: 'release: patch,release: minor,release: major'
          REQUIRED_LABELS_ANY_DESCRIPTION: "Select at least one label ['release: patch', 'release: minor', 'release: major']"

  bump-version:
    needs: enforce-label-version-release
    name: 'Bump: Version Increase'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: 'Save version to .env'
        run: |
          IS_MINOR_FOUND=$(echo "${{ github.event.pull_request.labels.*.name }}" | grep -c 'release: minor')
          IS_PATCH_FOUND=$(echo "${{ github.event.pull_request.labels.*.name }}" | grep -c 'release: patch')
          IS_MAJOR_FOUND=$(echo "${{ github.event.pull_request.labels.*.name }}" | grep -c 'release: major')

          if [ "${IS_MINOR_FOUND}" -gt 0 ]; then
            echo "version=minor" >> $GITHUB_ENV
            echo "Version: minor"
          elif [ "${IS_PATCH_FOUND}" -gt 0 ]; then
            echo "version=patch" >> $GITHUB_ENV
            echo "Version: patch"
          else
            echo "version=major" >> $GITHUB_ENV
            echo "Version: major"
          fi

      - name: 'Automated: Version Bump (package.json)'
        id: version-bump
        uses: phips28/gh-action-bump-version@v10.1.1
        with:
          version-type: ${{ env.version }}
          minor-wording: minor
          major-wording: major
          patch-wording: patch
          skip-tag: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
