name: 'Create tags and release'

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  # This will create automatic tags based on the last 50 comits and it will create latest release
  release:
    name: 'Create: tags and release'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
          release_name: 'Release <RELEASE_VERSION>'
          tag_prefix: 'v'

  # This will start build of the project
  build:
    name: 'Start: build'
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build

  # This will push the latest build of the project to npm
  publish-npm:
    name: 'Publish: npm public'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
      # - run: npm publish --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.npm_token}}
