name: 'Tests : unit / integration / e2e'
on:
  pull_request:
    types: [opened, edited, synchronize]
    paths-ignore:
      - 'test/**'
      - 'README.md'

jobs:
  # This will start unit/integration testing
  test-unit:
    name: 'Testing: Unit'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Cache dependencies

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
          path: ~/.npm

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm test

  # This will start the e2e tests with a live server
  test-e2e:
    name: 'Testing: End-to-end (e2e)'
    needs: test-unit
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      # Use cached dependencies

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
          path: ~/.npm

      - name: Install dependencies
        run: npm ci

      - name: Instal SAP CDS-DK
        run: npm i -g @sap/cds-dk && npm install -g ts-node

      - name: Start server and start e2e tests
        run: npm run start:server-and-test
